import { existsSync, readFileSync, writeFileSync, renameSync, mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { parse, stringify } from "yaml";

const root = resolve(import.meta.dirname, "..");
const openapiRoot = join(root, "openapi.yaml");
const outputDir = join(root, "openapi");
const check = process.argv.includes("--check");

function stableSchema(value) {
  if (Array.isArray(value)) return value.map(stableSchema);
  if (!value || typeof value !== "object") return value;
  const result = {};
  for (const [key, child] of Object.entries(value)) {
    if (key === "$id" || key === "$schema") continue;
    result[key] = stableSchema(child);
  }
  if (Array.isArray(result.allOf) && result.allOf.length === 1) return result.allOf[0];
  if (Array.isArray(result.anyOf) && result.anyOf.length > 0 && result.anyOf.every((item) => item && typeof item === "object" && typeof item.const === "string" && item.type === "string")) {
    const types = new Set(result.anyOf.map((item) => item.type));
    if (types.size === 1) return { ...Object.fromEntries(Object.entries(result).filter(([key]) => key !== "anyOf")), type: [...types][0], enum: result.anyOf.map((item) => item.const) };
  }
  return result;
}

function dump(value) {
  return stringify(value, { indent: 2, lineWidth: 0, nullStr: "null" });
}

function dumpGenerated(value) {
  return `# AUTO-GENERATED by scripts/generate-openapi.mjs. Do not edit manually.\n${dump(value)}`;
}

function writeOrCheck(path, content) {
  if (check) {
    const actual = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (actual !== content) {
      console.error(`Generated contract is stale: ${path}`);
      if (actual !== null) console.error(`existing bytes=${actual.length}, generated bytes=${content.length}`);
      process.exitCode = 1;
    }
    return;
  }
  const temporary = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporary, content, "utf8");
    renameSync(temporary, path);
  } finally {
    if (existsSync(temporary)) rmSync(temporary, { force: true });
  }
}

const operationSchemaRefs = {
  listEcomDetailsImageTemplates: { response: { "200": "EcomTemplatesResponse" } },
  testProviderConnection: { request: "TestProviderInput", response: { "200": "TestProviderConnectionResult" } },
  uploadAsset: { request: "UploadAssetInput" },
  updateAsset: { request: "UpdateAssetInput" },
  listPlanningConfigSnapshots: { response: { "200": "PlanningConfigSnapshotList" } },
  applyPlanningConfigSnapshot: { response: { "200": "ApplyPlanningConfigSnapshotResult" } },
  confirmStoryboard: { request: "ConfirmStoryboardInput" },
  createGenerationJobs: { request: "CreateGenerationJobInput", response: { "202": "GenerationJobsResponse" } },
  updateEditSessionMemory: { request: "UpdateEditSessionMemoryInput" },
  listEditReferenceAssets: { response: { "200": "EditReferenceAssetList" } },
  uploadEditReferenceAsset: { request: "UploadEditReferenceAssetInput" },
  createEditTurn: { request: "CreateEditTurnInput", response: { "202": "EditTurnQueuedResponse" } },
  selectEditSessionOutput: { request: "SelectEditSessionOutputInput" },
  approveEditTurn: { response: { "202": "ApproveEditTurnResponse" } },
};

function normalizePathSchemas(pathsDocument) {
  const paths = structuredClone(pathsDocument.paths ?? {});
  for (const pathItem of Object.values(paths)) {
    for (const operation of Object.values(pathItem ?? {})) {
      if (!operation || typeof operation !== "object" || !operation.operationId) continue;
      const mapping = operationSchemaRefs[operation.operationId];
      if (!mapping) continue;
      if (mapping.request && operation.requestBody?.content) {
        for (const media of Object.values(operation.requestBody.content)) media.schema = { $ref: `#/components/schemas/${mapping.request}` };
      }
      for (const [status, name] of Object.entries(mapping.response ?? {})) {
        const response = operation.responses?.[status];
        if (!response?.content) continue;
        for (const media of Object.values(response.content)) media.schema = { $ref: `#/components/schemas/${name}` };
      }
    }
  }
  return { paths };
}

mkdirSync(outputDir, { recursive: true });
const existing = parse(readFileSync(openapiRoot, "utf8"));
if (!check && !existsSync(join(outputDir, "paths.yaml"))) writeFileSync(join(outputDir, "paths.yaml"), dump({ paths: existing.paths }), "utf8");
if (!check && !existsSync(join(outputDir, "components.yaml"))) writeFileSync(join(outputDir, "components.yaml"), dump({ components: { parameters: existing.components?.parameters ?? {}, responses: existing.components?.responses ?? {} } }), "utf8");

const { API_SCHEMA_REGISTRY } = await import("../packages/contracts/dist/api-registry.js");
const schemas = {};
for (const [name, schema] of Object.entries(API_SCHEMA_REGISTRY)) schemas[name] = stableSchema(schema);
writeOrCheck(join(outputDir, "schemas.generated.yaml"), dumpGenerated({ components: { schemas } }));

const pathsSource = normalizePathSchemas(parse(readFileSync(join(outputDir, "paths.yaml"), "utf8")));
writeOrCheck(join(outputDir, "paths.yaml"), dump(pathsSource));
const componentsSource = parse(readFileSync(join(outputDir, "components.yaml"), "utf8"));
const bundled = {
  openapi: existing.openapi,
  info: existing.info,
  security: existing.security ?? [],
  servers: existing.servers ?? [],
  paths: pathsSource.paths,
  components: { ...(componentsSource.components ?? {}), schemas },
};
writeOrCheck(openapiRoot, dumpGenerated(bundled));

if (check) {
  const temp = mkdtempSync(join(tmpdir(), "ecomgen-contract-")).replaceAll("\\", "/");
  try {
    const generated = join(temp, "schema.d.ts");
    const result = spawnSync("pnpm", ["--filter", "@ecomgen/web", "exec", "openapi-typescript", "../../openapi.yaml", "-o", generated], { cwd: root, stdio: "inherit", shell: true });
    if (result.status !== 0) process.exitCode = result.status ?? 1;
    else if (readFileSync(generated, "utf8") !== readFileSync(join(root, "apps/web/src/api/schema.d.ts"), "utf8")) {
      console.error("Generated Web API types are stale: apps/web/src/api/schema.d.ts");
      process.exitCode = 1;
    }
  } finally { rmSync(temp, { recursive: true, force: true }); }
}
