/** 统一 query key 工厂，SSE 事件失效映射也以此为准。 */
export const qk = {
  health: ["health"] as const,
  templates: ["ecom-templates"] as const,
  userTemplates: ["user-templates"] as const,
  suites: ["suites"] as const,
  suiteCategories: ["suite-categories"] as const,
  suite: (id: string) => ["suites", id] as const,
  suiteForgeJob: (id: string) => ["suite-forge-jobs", id] as const,
  suiteForgeResult: (id: string) => ["suite-forge-jobs", id, "result"] as const,
  providers: ["providers"] as const,
  searchSources: ["search-sources"] as const,
  projects: (archived?: boolean) => ["projects", { archived: archived ?? false }] as const,
  project: (id: string) => ["projects", id] as const,
  libraryAssets: (filters: { kind: string; q: string }) => ["library-assets", filters] as const,
  storyboard: (id: string) => ["projects", id, "storyboard"] as const,
  planningSnapshots: (id: string) => ["projects", id, "planning-config-snapshots"] as const,
  job: (id: string) => ["jobs", id] as const,
  editTurn: (id: string) => ["edit-turns", id] as const,
  export: (id: string) => ["exports", id] as const,
  exports: (id: string) => ["projects", id, "exports"] as const,
};
