/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ecom-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEcomDetailsImageTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch: operations["updateProvider"];
        trace?: never;
    };
    "/providers/{providerId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProviderConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSearchSources"];
        put?: never;
        post: operations["createSearchSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSearchSource"];
        options?: never;
        head?: never;
        patch: operations["updateSearchSource"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["uploadAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch: operations["updateAsset"];
        trace?: never;
    };
    "/projects/{projectId}/planning-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlanningJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/planning-config-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listPlanningConfigSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/planning-config-snapshots/{snapshotId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                snapshotId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyPlanningConfigSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/copywriting-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCopywritingJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copywriting-jobs/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getCopywritingResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/storyboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getStoryboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/storyboard/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmStoryboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storyboard-items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteStoryboardItem"];
        options?: never;
        head?: never;
        patch: operations["updateStoryboardItem"];
        trace?: never;
    };
    "/projects/{projectId}/generation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGenerationJobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/outputs/{outputId}/edit-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEditSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["getEditSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEditSessionMemory"];
        trace?: never;
    };
    "/edit-sessions/{sessionId}/reference-assets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["listEditReferenceAssets"];
        put?: never;
        post: operations["uploadEditReferenceAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}/reference-assets/{referenceAssetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                referenceAssetId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteEditReferenceAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}/reference-assets/{referenceAssetId}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                referenceAssetId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteEditReferenceAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEditTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-sessions/{sessionId}/select-output": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectEditSessionOutput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-turns/{turnId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: string;
            };
            cookie?: never;
        };
        get: operations["getEditTurn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit-turns/{turnId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveEditTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Supersedes the original failed job as CANCELLED and queues a replacement job. Repeated retries on the same job respond with 409. */
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/export-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExportJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["getExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        get: operations["downloadAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/outputs/{outputId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        get: operations["downloadOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["downloadExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PlatformTarget: "TAOBAO" | "JD" | "PDD" | "DOUYIN" | "AMAZON" | "SHOPIFY";
        /** @enum {string} */
        TargetMarket: "CHINA_MAINLAND" | "HONG_KONG" | "MACAU" | "TAIWAN" | "UNITED_STATES" | "UNITED_KINGDOM" | "GERMANY" | "FRANCE" | "ITALY" | "SPAIN" | "JAPAN" | "SOUTH_KOREA";
        /** @enum {string} */
        StoryboardMode: "CREATIVE" | "PIXEL_PROTECTED";
        /** @enum {string} */
        AssetRole: "PRODUCT_TRUTH" | "PACKAGING" | "STYLE_REFERENCE" | "LAYOUT_REFERENCE";
        /** @enum {string} */
        UserAssetKind: "PRODUCT" | "REFERENCE";
        /** @enum {string} */
        ImageResolution: "1K" | "2K" | "4K";
        /** @enum {string} */
        ImageAspectRatio: "AUTO" | "1:1" | "3:4" | "4:3" | "16:9";
        /** @enum {string} */
        PlanningMode: "AI" | "MANUAL";
        /** @enum {string} */
        CopywritingTarget: "PRODUCT_DESCRIPTION" | "PLANNING_INSTRUCTION";
        /** @enum {string} */
        JobType: "PLAN" | "COPYWRITE" | "GENERATE" | "EXPORT" | "EDIT_PLAN" | "EDIT_GENERATE";
        /** @enum {string} */
        JobStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        ReasoningProtocolProfile: "openai" | "dashscope_qwen" | "openai_responses";
        /** @enum {string} */
        SearchSourceKind: "brave" | "tavily" | "searxng";
        /** @enum {string} */
        EditOperation: "PRECISE_INPAINT" | "PRODUCT_REPLACE" | "SCENE_ADJUST" | "OUTPAINT" | "NATURAL_FUSION";
        /** @enum {string} */
        EditExecutionMode: "MODEL_DIRECTED" | "MASKED" | "OUTPAINT" | "NEED_INPUT";
        /** @enum {string} */
        ReferenceSource: "PROJECT" | "TEMPORARY";
        /** @enum {string} */
        ReferencePurpose: "PRODUCT_APPEARANCE" | "PACKAGING" | "LABEL" | "STYLE" | "LAYOUT";
        /** @enum {string} */
        EditTurnStatus: "DRAFT" | "PLANNING" | "PLAN_READY" | "NEED_INPUT" | "AWAITING_CONFIRMATION" | "GENERATING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        EditSessionStatus: "ACTIVE" | "ARCHIVED";
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "CONFLICT" | "CAPABILITY_UNSUPPORTED" | "PROVIDER_NOT_CONFIGURED" | "RATE_LIMITED" | "INTERNAL_ERROR" | "PROVIDER_ERROR";
        EventEnvelope: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "job.updated" | "storyboard.updated" | "output.created" | "edit-session.updated" | "edit-turn.updated" | "export.updated" | "provider.updated";
            /** Format: uuid */
            projectId: string;
            /** Format: date-time */
            occurredAt: string;
            data: unknown;
        };
        ModelCapabilities: {
            supportsVision: boolean;
            supportsThinking: boolean;
            supportsTools: boolean;
            supportsStructuredOutput: boolean;
            imageApiKind: "openai_images" | "gemini" | "custom" | null;
        };
        ModelDefinition: {
            id: string;
        } & {
            supportsVision: boolean;
            supportsThinking: boolean;
            supportsTools: boolean;
            supportsStructuredOutput: boolean;
            imageApiKind: "openai_images" | "gemini" | "custom" | null;
        };
        Asset: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            role: components["schemas"]["AssetRole"];
            kind?: components["schemas"]["UserAssetKind"];
            url?: string;
            storagePath?: string;
            mimeType: string;
            originalName?: string;
            hash?: string;
            width?: number | null;
            height?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        AssetList: {
            items: components["schemas"]["Asset"][];
            nextCursor: string | null;
        };
        CopywritingResult: {
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            projectId: string;
            target: components["schemas"]["CopywritingTarget"];
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateCopywritingJobInput: {
            target: components["schemas"]["CopywritingTarget"];
            /** @description Unique key for an intentional copywriting run. */
            regenerationKey: string;
        };
        CreateExportJobInput: {
            outputIds?: string[];
            filenamePrefix?: string;
            platformTargets?: ("TAOBAO" | "JD" | "PDD" | "DOUYIN" | "AMAZON" | "SHOPIFY")[];
            /** @default false */
            includeDetailPageSlices: boolean;
        };
        CreatePlanningJobInput: {
            planningMode?: components["schemas"]["PlanningMode"];
            requestedTypes?: string[];
            imageTypes?: string[];
            userInstruction?: string;
            candidatesPerType?: number;
            targetImageCount?: number;
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            /** @description Unique key for an intentional re-planning run. */
            regenerationKey?: string;
        };
        CreateProjectInput: {
            name: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: unknown;
            };
            platformTargets?: ("TAOBAO" | "JD" | "PDD" | "DOUYIN" | "AMAZON" | "SHOPIFY")[];
            targetMarket?: "CHINA_MAINLAND" | "HONG_KONG" | "MACAU" | "TAIWAN" | "UNITED_STATES" | "UNITED_KINGDOM" | "GERMANY" | "FRANCE" | "ITALY" | "SPAIN" | "JAPAN" | "SOUTH_KOREA" | null;
            copyLanguage?: string | null;
            /** Format: uuid */
            reasoningProviderId: string;
            reasoningModelId: string;
            /** Format: uuid */
            imageProviderId: string;
            imageModelId: string;
            /** @enum {string} */
            defaultMode: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            candidatesPerType?: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled?: boolean;
        };
        CreateProviderInput: {
            name: string;
            /** Format: uri */
            baseUrl: string;
            /** @enum {string} */
            reasoningProtocol: "openai" | "dashscope_qwen" | "openai_responses";
            apiKey: string;
            models: components["schemas"]["ModelCapability"][];
        };
        CreateSearchSourceInput: {
            name: string;
            kind: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl?: string;
            apiKey?: string;
            priority: number;
            /** @default true */
            enabled: boolean;
        };
        EditReferenceAsset: {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["ReferenceSource"];
            purpose: components["schemas"]["ReferencePurpose"];
            role?: components["schemas"]["AssetRole"] | null;
            originalName: string;
            mimeType: string;
            hash: string;
            /** Format: date-time */
            createdAt: string;
            expiresAt?: string | null;
            url: string;
        };
        EditSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            currentOutputId: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            memorySummary: {
                summary?: string;
                constraints?: string[];
                /**
                 * Format: uuid
                 * @description Output node that owns the effective branch memory.
                 */
                sourceOutputId?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EditTurn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            baseOutputId: string;
            status: components["schemas"]["EditTurnStatus"];
            message: string;
            annotations: {
                [key: string]: unknown;
            };
            editMaskPath?: string | null;
            protectMaskPath?: string | null;
            referenceAssetIds: string[];
            referenceSelections: components["schemas"]["ReferenceSelection"][];
            plan?: {
                /** @enum {string} */
                operation?: "PRECISE_INPAINT" | "PRODUCT_REPLACE" | "SCENE_ADJUST" | "OUTPAINT" | "NATURAL_FUSION";
                executionMode?: components["schemas"]["EditExecutionMode"];
                userSummary?: string;
                prompt?: string;
                targetAnnotationIds?: string[];
                targetDescription?: string;
                targetConfidence?: number;
                clarification?: string | null;
                requiresConfirmation?: boolean;
                /** @enum {string} */
                compositePolicy?: "MASK_LOCKED" | "NATURAL_BLEND" | "OUTPAINT" | "PROVIDER_RESULT";
                memoryPatch?: {
                    [key: string]: unknown;
                };
            } | null;
            error?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                }[];
                /** Format: uuid */
                requestId: string;
            };
        };
        Export: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobId?: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            storagePath?: string | null;
            downloadUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ExportJobBundle: {
            job: components["schemas"]["Job"];
            export: {
                [key: string]: unknown;
            } | null;
        };
        Health: {
            status: string;
            /** @description Whether the server has a configured restricted visual-research search key. */
            webResearchAvailable: boolean;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "PLAN" | "COPYWRITE" | "GENERATE" | "EXPORT" | "EDIT_PLAN" | "EDIT_GENERATE";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            progress: number;
            retryable: boolean;
            requestFingerprint?: string | null;
            providerId?: string | null;
            modelId?: string | null;
            estimatedCost?: {
                [key: string]: unknown;
            } | null;
            actualCost?: {
                [key: string]: unknown;
            } | null;
            cancelRequested?: boolean;
            error?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ModelCapability: {
            id: string;
            supportsVision: boolean;
            supportsThinking: boolean;
            supportsTools: boolean;
            supportsStructuredOutput: boolean;
            imageApiKind?: "openai_images" | "gemini" | "custom" | null;
        };
        ModelRef: {
            /** Format: uuid */
            providerId: string;
            modelId: string;
        };
        Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            storyboardItemId: string;
            /** Format: uuid */
            jobId: string;
            candidateIndex?: number;
            generationSnapshot?: {
                /** Format: uuid */
                providerId?: string;
                modelId?: string;
                resolution?: components["schemas"]["ImageResolution"];
                aspectRatio?: components["schemas"]["ImageAspectRatio"];
                size?: string;
                candidateIndex?: number;
                revision?: string;
            } | null;
            url?: string;
            storagePath?: string;
            parentOutputId?: string | null;
            rootOutputId?: string | null;
            editSessionId?: string | null;
            editTurnId?: string | null;
            generationBatchId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PlanningConfigSnapshot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            sourceJobId: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: unknown;
            };
            platformTargets: ("TAOBAO" | "JD" | "PDD" | "DOUYIN" | "AMAZON" | "SHOPIFY")[];
            targetMarket: "CHINA_MAINLAND" | "HONG_KONG" | "MACAU" | "TAIWAN" | "UNITED_STATES" | "UNITED_KINGDOM" | "GERMANY" | "FRANCE" | "ITALY" | "SPAIN" | "JAPAN" | "SOUTH_KOREA" | null;
            copyLanguage: string | null;
            reasoningProviderId: string | null;
            reasoningModelId: string | null;
            imageProviderId: string | null;
            imageModelId: string | null;
            /** @enum {string} */
            defaultMode: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution: components["schemas"]["ImageResolution"];
            imageAspectRatio: components["schemas"]["ImageAspectRatio"];
            candidatesPerType: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled: boolean;
            archivedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            cover?: components["schemas"]["ProjectCover"];
        };
        ProjectCover: {
            productAssetId: string | null;
            coverOutputId: string | null;
            previewOutputIds: string[];
            outputCount: number;
        };
        ProjectDetail: components["schemas"]["Project"] & {
            assets: components["schemas"]["Asset"][];
            storyboard: {
                [key: string]: unknown;
            } | null;
            items: components["schemas"]["StoryboardItem"][];
            outputs: components["schemas"]["Output"][];
            jobs: components["schemas"]["Job"][];
        };
        ProjectList: {
            items: (components["schemas"]["Project"] & {
                [key: string]: unknown;
            })[];
            nextCursor: string | null;
        };
        ProviderConfig: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uri */
            baseUrl: string;
            /** @enum {string} */
            reasoningProtocol: "openai" | "dashscope_qwen" | "openai_responses";
            hasApiKey: boolean;
            models: components["schemas"]["ModelCapability"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProviderList: {
            items: components["schemas"]["ProviderConfig"][];
            nextCursor: string | null;
        };
        ReferenceSelection: {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["ReferenceSource"];
            purpose: components["schemas"]["ReferencePurpose"];
            order: number;
        };
        SearchSourceConfig: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl: string;
            /** @description Lower values are searched first. */
            priority: number;
            enabled: boolean;
            hasApiKey: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SearchSourceList: {
            items: components["schemas"]["SearchSourceConfig"][];
            nextCursor: string | null;
        };
        Storyboard: {
            /** Format: uuid */
            projectId: string;
            version: number;
            /** @enum {string} */
            status: "DRAFT" | "CONFIRMED";
            campaignStyleLock: string;
            items?: components["schemas"]["StoryboardItem"][];
        };
        StoryboardBundle: {
            storyboard: {
                [key: string]: unknown;
            } | null;
            items: components["schemas"]["StoryboardItem"][];
        };
        StoryboardItem: {
            /** Format: uuid */
            id: string;
            /** @description Immutable ecom-details-image template ID; it cannot be changed after planning. */
            assetType: string;
            displayName: string;
            templateVariant?: string | null;
            candidateCount: number;
            /** Format: uuid */
            imageProviderId?: string;
            imageModelId?: string;
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            referencedAssets?: string[];
            /** @enum {string} */
            mode: "CREATIVE" | "PIXEL_PROTECTED";
            /** @enum {string} */
            status: "DRAFT" | "CONFIRMED" | "GENERATING" | "GENERATED";
            /** @description Final image-generation prompt produced by Pi Agent. Worker prefixes selected image roles in their actual request order before sending it to the image model. */
            promptInstruction: string;
            factClaims?: string[];
            riskFlags: string[];
        };
        UpdateProjectInput: {
            name?: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: unknown;
            };
            platformTargets?: ("TAOBAO" | "JD" | "PDD" | "DOUYIN" | "AMAZON" | "SHOPIFY")[];
            targetMarket?: "CHINA_MAINLAND" | "HONG_KONG" | "MACAU" | "TAIWAN" | "UNITED_STATES" | "UNITED_KINGDOM" | "GERMANY" | "FRANCE" | "ITALY" | "SPAIN" | "JAPAN" | "SOUTH_KOREA" | null;
            copyLanguage?: string | null;
            reasoningModel?: components["schemas"]["ModelRef"];
            imageModel?: components["schemas"]["ModelRef"];
            /** @enum {string} */
            defaultMode?: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            candidatesPerType?: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled?: boolean;
            /** @description Archive or restore the project. */
            archived?: boolean;
        };
        UpdateProviderInput: {
            name?: string;
            /** Format: uri */
            baseUrl?: string;
            /** @enum {string} */
            reasoningProtocol?: "openai" | "dashscope_qwen" | "openai_responses";
            apiKey?: string;
            models?: components["schemas"]["ModelCapability"][];
        };
        UpdateSearchSourceInput: {
            name?: string;
            kind?: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl?: string;
            apiKey?: string;
            priority?: number;
            enabled?: boolean;
        };
        UpdateStoryboardItemInput: {
            /** @description Immutable ecom-details-image template ID; it cannot be changed after planning. */
            assetType?: string;
            displayName?: string;
            templateVariant?: string | null;
            candidateCount?: number;
            imageModel?: components["schemas"]["ModelRef"];
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            referencedAssets?: string[];
            /** @enum {string} */
            mode?: "CREATIVE" | "PIXEL_PROTECTED";
            /** @description Editable final image-generation prompt. Worker prefixes selected image roles in their actual request order before sending it to the image model. */
            promptInstruction?: string;
        };
        AiPlanningInput: {
            planningMode?: components["schemas"]["PlanningMode"];
            requestedTypes?: string[];
            imageTypes?: string[];
            userInstruction?: string;
            candidatesPerType?: number;
            targetImageCount?: number;
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            regenerationKey?: string;
        };
        ApplyPlanningConfigSnapshotResult: {
            project: components["schemas"]["Project"];
            snapshot: components["schemas"]["PlanningConfigSnapshot"];
        };
        ApproveEditTurnResponse: {
            job: components["schemas"]["Job"];
            turn: components["schemas"]["EditTurn"];
        };
        ConfirmStoryboardInput: {
            version?: number;
        };
        CreateEditTurnInput: {
            /** Format: uuid */
            baseOutputId?: string;
            message: string;
            annotations?: string;
            /** Format: binary */
            editMask?: string;
            /** Format: binary */
            protectMask?: string;
            referenceSelections?: string;
        };
        CreateExportJobRequest: {
            outputIds?: string[];
            filenamePrefix?: string;
            platformTargets?: components["schemas"]["PlatformTarget"][];
            includeDetailPageSlices?: boolean;
        };
        CreateGenerationJobInput: {
            storyboardItemIds: string[];
            /** Format: uuid */
            generationBatchId?: string;
            revision?: string;
            generationConfig?: {
                imageResolution?: components["schemas"]["ImageResolution"];
                imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
                candidateCount?: number;
                imageModel?: components["schemas"]["ModelRef"];
            };
        };
        EcomTemplateItem: {
            id: string;
            upstreamNumber: number;
            name: string;
            keywords: string[];
            trigger_phrases: string[];
            prompt_template: {
                [key: string]: string;
            };
            defaults: {
                [key: string]: string;
            };
            category_tips: {
                [key: string]: string;
            };
            /** @enum {string} */
            defaultSize: "1024x1024" | "1024x1536";
            variants?: {
                [key: string]: unknown;
            };
        };
        EcomTemplatesResponse: {
            source: {
                /** Format: uri */
                repository: string;
                commit: string;
                sourcePath: string;
            };
            items: components["schemas"]["EcomTemplateItem"][];
        };
        EditGenerationConfigInput: {
            /** Format: uuid */
            reasoningProviderId: string;
            reasoningModelId: string;
            /** Format: uuid */
            imageProviderId: string;
            imageModelId: string;
            imageResolution?: components["schemas"]["ImageResolution"];
            candidateCount?: number;
        };
        EditReferenceAssetList: {
            items: components["schemas"]["EditReferenceAsset"][];
            suggestedSelections: components["schemas"]["ReferenceSelection"][];
        };
        EditTurnQueuedResponse: {
            /** Format: uuid */
            turnId: string;
            /** Format: uuid */
            planJobId: string;
            status: components["schemas"]["EditTurnStatus"];
        };
        GenerationJobsResponse: {
            jobs: components["schemas"]["Job"][];
        };
        ManualPlanningInput: {
            /** @constant */
            planningMode: "MANUAL";
            requestedTypes: string[];
            userInstruction?: string;
            candidatesPerType?: number;
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            regenerationKey?: string;
        };
        PlanningConfigSnapshotList: components["schemas"]["PlanningConfigSnapshot"][];
        SelectEditSessionOutputInput: {
            /** Format: uuid */
            outputId: string;
        };
        TestProviderConnectionResult: {
            ok: boolean;
            /** Format: uuid */
            providerId: string;
            modelId: string;
            kind: string;
            latencyMs: number;
            models: string[] | null;
            modelAvailable: boolean | null;
        };
        TestProviderInput: {
            modelId: string;
            /** @enum {string} */
            kind?: "reasoning" | "image";
        };
        UpdateAssetInput: {
            role?: components["schemas"]["AssetRole"];
            kind?: components["schemas"]["UserAssetKind"];
        };
        UpdateEditSessionMemoryInput: {
            /** Format: uuid */
            outputId?: string;
            summary: string;
            constraints: string[];
        };
        UploadAssetInput: {
            /** Format: binary */
            file: string;
            role?: components["schemas"]["AssetRole"];
            kind?: components["schemas"]["UserAssetKind"];
        };
        UploadEditReferenceAssetInput: {
            /** Format: binary */
            file: string;
            purpose: components["schemas"]["ReferencePurpose"];
        };
    };
    responses: {
        /** @description Request does not match the schema. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Current resource state rejects this operation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The selected model lacks a requested capability. */
        CapabilityUnsupported: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Provider connectivity or protocol failure. */
        ProviderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ProviderId: string;
        ProjectId: string;
        AssetId: string;
        StoryboardItemId: string;
        JobId: string;
        OutputId: string;
        ExportId: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listEcomDetailsImageTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Structured templates adapted from the pinned ecom-details-image upstream Skill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EcomTemplatesResponse"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider configurations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderInput"];
            };
        };
        responses: {
            /** @description Provider created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfig"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderInput"];
            };
        };
        responses: {
            /** @description Provider updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    testProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestProviderInput"];
            };
        };
        responses: {
            /** @description Provider connectivity result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestProviderConnectionResult"];
                };
            };
            502: components["responses"]["ProviderError"];
        };
    };
    listSearchSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search source configurations in execution priority order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceList"];
                };
            };
        };
    };
    createSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSearchSourceInput"];
            };
        };
        responses: {
            /** @description Search source created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceConfig"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    deleteSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search source deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSearchSourceInput"];
            };
        };
        responses: {
            /** @description Search source updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Project updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
        };
    };
    uploadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadAssetInput"];
            };
        };
        responses: {
            /** @description Asset uploaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetInput"];
            };
        };
        responses: {
            /** @description Asset updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    createPlanningJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanningJobInput"];
            };
        };
        responses: {
            /** @description Planning job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            422: components["responses"]["CapabilityUnsupported"];
        };
    };
    listPlanningConfigSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent planning configuration snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningConfigSnapshotList"];
                };
            };
        };
    };
    applyPlanningConfigSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Applied planning configuration snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyPlanningConfigSnapshotResult"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    createCopywritingJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCopywritingJobInput"];
            };
        };
        responses: {
            /** @description Existing copywriting job reused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Copywriting job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["CapabilityUnsupported"];
        };
    };
    getCopywritingResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated copywriting result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopywritingResult"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current storyboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardBundle"];
                };
            };
        };
    };
    confirmStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfirmStoryboardInput"];
            };
        };
        responses: {
            /** @description Storyboard frozen for generation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storyboard"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteStoryboardItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft storyboard item deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateStoryboardItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoryboardItemInput"];
            };
        };
        responses: {
            /** @description Storyboard item updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardItem"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    createGenerationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationJobInput"];
            };
        };
        responses: {
            /** @description Generation job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobsResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    createEditSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edit session created or reused. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditSession"];
                };
            };
        };
    };
    getEditSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edit session and turns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditSession"] & {
                        turns: components["schemas"]["EditTurn"][];
                        versions?: components["schemas"]["Output"][];
                    };
                };
            };
        };
    };
    updateEditSessionMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEditSessionMemoryInput"];
            };
        };
        responses: {
            /** @description Updated edit session memory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditSession"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEditReferenceAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project and temporary reference assets available to this edit session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditReferenceAssetList"];
                };
            };
        };
    };
    uploadEditReferenceAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadEditReferenceAssetInput"];
            };
        };
        responses: {
            /** @description Temporary reference asset uploaded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditReferenceAsset"];
                };
            };
        };
    };
    deleteEditReferenceAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                referenceAssetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temporary reference asset deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    promoteEditReferenceAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                referenceAssetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temporary reference asset saved to the project. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditReferenceAsset"];
                };
            };
        };
    };
    createEditTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateEditTurnInput"];
            };
        };
        responses: {
            /** @description Edit plan queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditTurnQueuedResponse"];
                };
            };
        };
    };
    selectEditSessionOutput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectEditSessionOutputInput"];
            };
        };
        responses: {
            /** @description Current edit output changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditSession"];
                };
            };
        };
    };
    getEditTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edit turn state and plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditTurn"];
                };
            };
        };
    };
    approveEditTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edit generation queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveEditTurnResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New retry job queued; the original job is now CANCELLED. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    createExportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportJobInput"];
            };
        };
        responses: {
            /** @description Export job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobBundle"];
                };
            };
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export package state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    downloadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original asset bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadOutput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ZIP package bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    subscribeEvents: {
        parameters: {
            query: {
                projectId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
