/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ecom-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEcomDetailsImageTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch: operations["updateProvider"];
        trace?: never;
    };
    "/providers/{providerId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProviderConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSearchSources"];
        put?: never;
        post: operations["createSearchSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSearchSource"];
        options?: never;
        head?: never;
        patch: operations["updateSearchSource"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["uploadAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch: operations["updateAsset"];
        trace?: never;
    };
    "/projects/{projectId}/planning-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlanningJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/storyboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getStoryboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/storyboard/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmStoryboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storyboard-items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteStoryboardItem"];
        options?: never;
        head?: never;
        patch: operations["updateStoryboardItem"];
        trace?: never;
    };
    "/projects/{projectId}/generation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGenerationJobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outputs/{outputId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reviewOutput"];
        trace?: never;
    };
    "/projects/{projectId}/export-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExportJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["getExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        get: operations["downloadAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/outputs/{outputId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        get: operations["downloadOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["downloadExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            /** @description Whether the server has a configured restricted visual-research search key. */
            webResearchAvailable: boolean;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: Record<string, never>[];
                /** Format: uuid */
                requestId: string;
            };
        };
        ProviderConfig: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uri */
            baseUrl: string;
            /** @enum {string} */
            reasoningProtocol: "openai" | "dashscope_qwen";
            hasApiKey: boolean;
            models: components["schemas"]["ModelCapability"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ModelCapability: {
            id: string;
            supportsVision: boolean;
            supportsThinking: boolean;
            supportsTools: boolean;
            supportsStructuredOutput: boolean;
            /** @enum {string|null} */
            imageApiKind?: "openai_images" | "custom" | null;
        };
        CreateProviderInput: {
            name: string;
            /** Format: uri */
            baseUrl: string;
            /** @enum {string} */
            reasoningProtocol: "openai" | "dashscope_qwen";
            apiKey: string;
            models: components["schemas"]["ModelCapability"][];
        };
        UpdateProviderInput: components["schemas"]["CreateProviderInput"];
        ProviderList: {
            items: components["schemas"]["ProviderConfig"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        SearchSourceKind: "brave" | "tavily" | "searxng";
        SearchSourceConfig: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl: string;
            /** @description Lower values are searched first. */
            priority: number;
            enabled: boolean;
            hasApiKey: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSearchSourceInput: {
            name: string;
            kind: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl?: string;
            apiKey?: string;
            priority: number;
            /** @default true */
            enabled: boolean;
        };
        UpdateSearchSourceInput: {
            name?: string;
            kind?: components["schemas"]["SearchSourceKind"];
            /** Format: uri */
            baseUrl?: string;
            apiKey?: string;
            priority?: number;
            enabled?: boolean;
        };
        SearchSourceList: {
            items: components["schemas"]["SearchSourceConfig"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        ImageResolution: "1K" | "2K" | "4K";
        /** @enum {string} */
        ImageAspectRatio: "AUTO" | "1:1" | "3:4" | "4:3" | "16:9";
        /** @enum {string} */
        PlanningMode: "AI" | "MANUAL";
        /** @enum {string} */
        UserAssetKind: "PRODUCT" | "REFERENCE";
        ProjectCover: {
            /** Format: uuid */
            productAssetId: string | null;
            /** Format: uuid */
            coverOutputId: string | null;
            previewOutputIds: string[];
            outputCount: number;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: string;
            };
            platformTargets: ("DOMESTIC" | "AMAZON")[];
            /** Format: uuid */
            reasoningProviderId: string;
            reasoningModelId: string;
            /** Format: uuid */
            imageProviderId: string;
            imageModelId: string;
            /** @enum {string} */
            defaultMode: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution: components["schemas"]["ImageResolution"];
            imageAspectRatio: components["schemas"]["ImageAspectRatio"];
            candidatesPerType: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            cover?: components["schemas"]["ProjectCover"];
        };
        ProjectDetail: components["schemas"]["Project"] & {
            assets: components["schemas"]["Asset"][];
            storyboard: Record<string, never> | null;
            items: components["schemas"]["StoryboardItem"][];
            outputs: components["schemas"]["Output"][];
            jobs: components["schemas"]["Job"][];
        };
        ModelRef: {
            /** Format: uuid */
            providerId: string;
            modelId: string;
        };
        CreateProjectInput: {
            name: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: string;
            };
            platformTargets: ("DOMESTIC" | "AMAZON")[];
            /** Format: uuid */
            reasoningProviderId: string;
            reasoningModelId: string;
            /** Format: uuid */
            imageProviderId: string;
            imageModelId: string;
            /** @enum {string} */
            defaultMode: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            candidatesPerType?: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled?: boolean;
        };
        UpdateProjectInput: {
            name?: string;
            category?: string | null;
            productDescription?: string | null;
            verifiedFacts?: string[];
            prohibitedClaims?: string[];
            brandGuidelines?: {
                [key: string]: string;
            };
            platformTargets?: ("DOMESTIC" | "AMAZON")[];
            reasoningModel?: components["schemas"]["ModelRef"];
            imageModel?: components["schemas"]["ModelRef"];
            /** @enum {string} */
            defaultMode?: "CREATIVE" | "PIXEL_PROTECTED";
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            candidatesPerType?: number;
            /** @description Enable restricted visual-direction web research during Agent planning. */
            webResearchEnabled?: boolean;
        };
        ProjectList: {
            items: (components["schemas"]["Project"] & Record<string, never>)[];
            nextCursor: string | null;
        };
        /** @enum {string} */
        AssetRole: "PRODUCT_TRUTH" | "PACKAGING" | "STYLE_REFERENCE" | "LAYOUT_REFERENCE";
        Asset: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            role: components["schemas"]["AssetRole"];
            kind?: components["schemas"]["UserAssetKind"];
            url?: string;
            storagePath?: string;
            mimeType: string;
            width?: number | null;
            height?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        AssetList: {
            items: components["schemas"]["Asset"][];
            nextCursor: string | null;
        };
        CreatePlanningJobInput: {
            planningMode?: components["schemas"]["PlanningMode"];
            requestedTypes?: string[];
            imageTypes?: string[];
            userInstruction?: string;
            candidatesPerType?: number;
            imageResolution?: components["schemas"]["ImageResolution"];
            imageAspectRatio?: components["schemas"]["ImageAspectRatio"];
            /** @description Unique key for an intentional re-planning run. */
            regenerationKey?: string;
        };
        Storyboard: {
            /** Format: uuid */
            projectId: string;
            version: number;
            /** @enum {string} */
            status: "DRAFT" | "CONFIRMED";
            campaignStyleLock: string;
            items?: components["schemas"]["StoryboardItem"][];
        };
        StoryboardBundle: {
            storyboard: Record<string, never> | null;
            items: components["schemas"]["StoryboardItem"][];
        };
        StoryboardItem: {
            /** Format: uuid */
            id: string;
            /** @description Immutable ecom-details-image template ID; it cannot be changed after planning. */
            assetType: string;
            displayName: string;
            templateVariant?: string | null;
            candidateCount: number;
            referencedAssets?: string[];
            /** @enum {string} */
            mode: "CREATIVE" | "PIXEL_PROTECTED";
            /** @enum {string} */
            status: "DRAFT" | "CONFIRMED" | "GENERATING" | "GENERATED";
            /** @description Final image-generation prompt produced by Pi Agent; Worker sends this text to the image model without template concatenation. */
            promptInstruction: string;
            factClaims?: string[];
            riskFlags: string[];
        };
        UpdateStoryboardItemInput: {
            /** @description Immutable ecom-details-image template ID; it cannot be changed after planning. */
            assetType?: string;
            displayName?: string;
            templateVariant?: string | null;
            candidateCount?: number;
            referencedAssets?: string[];
            /** @enum {string} */
            mode?: "CREATIVE" | "PIXEL_PROTECTED";
            /** @description Editable final image-generation prompt; the saved value is sent as-is to the image model. */
            promptInstruction?: string;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "PLAN" | "GENERATE" | "EXPORT";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            progress: number;
            retryable: boolean;
            requestFingerprint?: string | null;
            /** Format: uuid */
            providerId?: string | null;
            modelId?: string | null;
            estimatedCost?: Record<string, never> | null;
            actualCost?: Record<string, never> | null;
            cancelRequested?: boolean;
            error?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            storyboardItemId: string;
            candidateIndex?: number;
            generationSnapshot?: {
                resolution?: components["schemas"]["ImageResolution"];
                aspectRatio?: components["schemas"]["ImageAspectRatio"];
                size?: string;
                candidateIndex?: number;
            } | null;
            url?: string;
            storagePath?: string;
            /** @enum {string} */
            reviewDecision: "SELECTED" | "REJECTED" | "NEEDS_REVIEW";
            reviewNote?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateExportJobInput: {
            outputIds?: string[];
            filenamePrefix?: string;
            platformTargets?: ("DOMESTIC" | "AMAZON")[];
            /** @default false */
            includeDetailPageSlices: boolean;
        };
        Export: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobId?: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            storagePath?: string | null;
            downloadUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ExportJobBundle: {
            job: components["schemas"]["Job"];
            export: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Request does not match the schema. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Current resource state rejects this operation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The selected model lacks a requested capability. */
        CapabilityUnsupported: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Provider connectivity or protocol failure. */
        ProviderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ProviderId: string;
        ProjectId: string;
        AssetId: string;
        StoryboardItemId: string;
        JobId: string;
        OutputId: string;
        ExportId: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listEcomDetailsImageTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Structured templates adapted from the pinned ecom-details-image upstream Skill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source: {
                            /** Format: uri */
                            repository: string;
                            commit: string;
                            sourcePath: string;
                        };
                        items: {
                            /** @example hero-image */
                            id: string;
                            upstreamNumber: number;
                            name: string;
                            keywords: string[];
                            trigger_phrases: string[];
                            prompt_template: {
                                [key: string]: string;
                            };
                            defaults: {
                                [key: string]: string;
                            };
                            variants: {
                                [key: string]: Record<string, never>;
                            };
                            category_tips: {
                                [key: string]: string;
                            };
                            /** @enum {string} */
                            defaultSize: "1024x1024" | "1024x1536";
                        }[];
                    };
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider configurations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderInput"];
            };
        };
        responses: {
            /** @description Provider created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfig"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderInput"];
            };
        };
        responses: {
            /** @description Provider updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    testProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    modelId: string;
                    /**
                     * @default image
                     * @enum {string}
                     */
                    kind?: "reasoning" | "image";
                };
            };
        };
        responses: {
            /** @description Provider connectivity result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        /** Format: uuid */
                        providerId: string;
                        modelId: string;
                        /** @enum {string} */
                        kind: "reasoning" | "image";
                        latencyMs: number;
                        modelAvailable?: boolean | null;
                    };
                };
            };
            502: components["responses"]["ProviderError"];
        };
    };
    listSearchSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search source configurations in execution priority order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceList"];
                };
            };
        };
    };
    createSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSearchSourceInput"];
            };
        };
        responses: {
            /** @description Search source created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceConfig"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    deleteSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search source deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSearchSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSearchSourceInput"];
            };
        };
        responses: {
            /** @description Search source updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourceConfig"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description Project updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
        };
    };
    uploadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    role?: components["schemas"]["AssetRole"];
                    kind?: components["schemas"]["UserAssetKind"];
                };
            };
        };
        responses: {
            /** @description Asset uploaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role?: components["schemas"]["AssetRole"];
                    kind?: components["schemas"]["UserAssetKind"];
                };
            };
        };
        responses: {
            /** @description Asset updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    createPlanningJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanningJobInput"];
            };
        };
        responses: {
            /** @description Planning job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            422: components["responses"]["CapabilityUnsupported"];
        };
    };
    getStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current storyboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardBundle"];
                };
            };
        };
    };
    confirmStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    version?: number;
                };
            };
        };
        responses: {
            /** @description Storyboard frozen for generation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storyboard"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteStoryboardItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft storyboard item deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateStoryboardItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["StoryboardItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoryboardItemInput"];
            };
        };
        responses: {
            /** @description Storyboard item updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardItem"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    createGenerationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    storyboardItemIds: string[];
                    revision?: string;
                };
            };
        };
        responses: {
            /** @description Generation job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobs: components["schemas"]["Job"][];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New retry job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    reviewOutput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reviewDecision?: "SELECTED" | "REJECTED" | "NEEDS_REVIEW";
                    reviewNote?: string;
                    /** @enum {string} */
                    decision?: "SELECTED" | "REJECTED" | "NEEDS_REVIEW";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Output review updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Output"];
                };
            };
        };
    };
    createExportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportJobInput"];
            };
        };
        responses: {
            /** @description Export job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobBundle"];
                };
            };
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export package state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    downloadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original asset bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadOutput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outputId: components["parameters"]["OutputId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    downloadExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ZIP package bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    subscribeEvents: {
        parameters: {
            query: {
                projectId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
